import "inspectable.idl";
import "Windows.Foundation.idl";
import "Windows.UI.idl";
import "Windows.UI.Xaml.Data.idl";
import "Windows.UI.Xaml.CustomAttributes.idl";

namespace DataBinding
{
	interface INumber;
	
	interface INumberOverrides;
	
	interface INumberFactory;
	
	runtimeclass Number;	
}

namespace DataBinding
{
	[exclusiveto(Number)]
	[uuid(5b197688-2f57-4d01-92cd-a888f10dcd90)]
	[version(0x00000001)]
	interface INumber : IInspectable
	{
		[propget]
		HRESULT Value([out, retval] INT32* value);
		[propput]
		HRESULT Value([in] INT32 value);
	}

	[exclusiveto(Number)]
	[uuid(12b0eeee-76ed-47af-8247-610025184b58)]
	[version(0x00000001)]
	interface INumberOverrides : IInspectable
	{
		HRESULT GetValue([out, retval] INT32* value);
	}

	[exclusiveto(Number)]
	[uuid(29f9bd09-d452-49bf-99f9-59f328103cbd)]
	[version(0x00000001)]
	interface INumberFactory : IInspectable
	{
		[overload("CreateInstance")]HRESULT CreateInstance0([in] IInspectable* outer, [out] IInspectable** inner, [out, retval] Number** result);
		[overload("CreateInstance")]HRESULT CreateInstance1([in] int value, [in] IInspectable* outer, [out] IInspectable** inner, [out, retval] Number** result);
	}

	[bindable]
	[composable(DataBinding.INumberFactory, public, 1.0)]
	[marshaling_behavior(agile)]
	[threading(both)]
	[version(0x00000001)]
	runtimeclass Number
	{
		[default] interface INumber;
		[overridable][version(0x00000001)] interface INumberOverrides;
		interface Windows.UI.Xaml.Data.INotifyPropertyChanged;
	}
}