import "inspectable.idl";
import "Windows.UI.Xaml.CustomAttributes.idl";

#define VERSION 0x00000001

namespace TestComponentWRL
{
	interface ITestClass;
	interface ITestClassFactory;
	runtimeclass TestClass;
}

namespace TestComponentWRL
{
	[exclusiveto(TestClass)]
	[version(VERSION)]
	[uuid(67214cd3-3c60-4844-aa3b-a234f99f3c47)]
	interface ITestClass : IInspectable
	{
		[propget]
		HRESULT Int([out, retval] INT32* result);

		[propget]
		HRESULT Str([out, retval] HSTRING* result);
	};

	[exclusiveto(TestClass)]
	[version(VERSION)]
	[uuid(ba773d38-ef3f-40bb-b212-f52e7f0245c0)]
	interface ITestClassFactory : IInspectable
	{
		HRESULT CreateInstance([in] INT32 value, [out, retval] TestClass** result);
	};

	[activatable(VERSION)]
	[activatable(ITestClassFactory, VERSION)]
	[bindable]
	[marshaling_behavior(agile)]
	[threading(both)]
	[version(VERSION)]
	runtimeclass TestClass
	{
		[default]
		interface ITestClass;
	}
}
