import "inspectable.idl";
import "Windows.ApplicationModel.background.idl";

#define VERSION 0x00000001

namespace RAWinRT
{
	namespace WRL

	{
		interface ITestTask;
		runtimeclass TestTask;
	}
}

namespace RAWinRT
	{
		namespace WRL
		{
			[exclusiveto(TestTask)]
			[uuid(048d938b-b235-432e-9092-20d703fe0b68)]
			[version(VERSION)]
			interface ITestTask : IInspectable
			{

			};

			[activatable(VERSION)]
			[marshaling_behavior(agile)]
			[threading(both)]
			[version(VERSION)]
			runtimeclass TestTask
			{
				[default]
				interface ITestTask;

				interface Windows.ApplicationModel.Background.IBackgroundTask;
			};
		}
	}
