import "inspectable.idl";
import "Windows.ApplicationModel.background.idl";

#define VERSION 0x00000001

namespace RAWinRT
{
	namespace WRL
	{
		interface ITestTask;
		runtimeclass TestTask;
	}
}

namespace RAWinRT
	{
		namespace WRL
		{
			[activatable(VERSION)]
			[marshaling_behavior(agile)]
			[threading(both)]
			[version(VERSION)]
			runtimeclass TestTask
			{
				[default]
				interface Windows.ApplicationModel.Background.IBackgroundTask;
			};
		}
	}
